const enums = {
  category: [
    "Saloon / Sedan",
    "Hatchback / Crossover",
    "Estate / Wagon",
    "Sports Car / Coupe",
    "SUV / Off-roader",
    "Cabriolet / Roadster",
    "Pickup truck",
    "Van / Minibus",
    "Cargo",
    "other",
  ],
  color: [
    "White",
    "Black",
    "Blue",
    "Beige",
    "Brown",
    "Green",
    "Red",
    "Gray",
    "Silver",
    "Gold",
    "Violet",
    "Pink",
    "Yellow",
    "Orange",
    "Turquoise",
    "other",
  ],
  condition: ["Used", "New", "Damaged", "other"],
  doors: ["2/3", "4/5", "other"],
  fuelType: [
    "Petrol",
    "Diesel",
    "Hybrid",
    "Plug-in Hybrid",
    "Electric",
    "LPG",
    "other",
  ],
  location: [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "other",
  ],
  make: [
    "Alfa-Romeo",
    "Aston-Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Cadillac",
    "Chevrolet",
    "Citroen",
    "Dacia",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Koenigsegg",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Opel",
    "Pagani",
    "Peugeot",
    "Pontiac",
    "Porsche",
    "Renaut",
    "Rolls-Royce",
    "Saab",
    "Seat",
    "Skoda",
    "Smart",
    "Ssangyong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Trabant",
    "Volkswagen",
    "Volvo",
    "other",
  ],
  seats: ["2", "4", "5", "6", "7", "other"],
  transmission: ["Manual", "Automatic", "Semi-automatic", "other"],
};

module.exports = enums;
